FROM node:22 AS build
WORKDIR /app

ARG VITE_APP_ZITADEL_ISSUER
ENV VITE_APP_ZITADEL_ISSUER=${VITE_APP_ZITADEL_ISSUER}

ARG VITE_APP_ZITADEL_CLIENT_ID
ENV VITE_APP_ZITADEL_CLIENT_ID=${VITE_APP_ZITADEL_CLIENT_ID}

ARG VITE_APP_ZITADEL_PROJECT_RESOURCE_ID
ENV VITE_APP_ZITADEL_PROJECT_RESOURCE_ID=${VITE_APP_ZITADEL_PROJECT_RESOURCE_ID}

ARG VITE_APP_MODULE_CORE_API_PREFIX
ENV VITE_APP_MODULE_CORE_API_PREFIX=${VITE_APP_MODULE_CORE_API_PREFIX}

ARG VITE_APP_BACKEND_HOST
ENV VITE_APP_BACKEND_HOST=${VITE_APP_BACKEND_HOST}

ARG VITE_APP_ZITADEL_ENABLED
ENV VITE_APP_ZITADEL_ENABLED=${VITE_APP_ZITADEL_ENABLED}

ARG VITE_APP_APP_VERSION
ENV VITE_APP_APP_VERSION=${VITE_APP_APP_VERSION}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build-only

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]